#python prepare_dataset.py configuration_ISBI_three_1.txt
#python prepare_dataset.py configuration_ISBI_three_2.txt
#python prepare_dataset.py configuration_ISBI_three_3.txt
#python prepare_dataset.py configuration_ISBI_three_4.txt
#python prepare_dataset.py configuration_ISBI_three_5.txt
#python prepare_dataset.py configuration_ISBI_three_6.txt
#python prepare_dataset.py configuration_ISBI_three_7.txt

python run_training.py configuration_ISBI_three_1.txt
python run_training.py configuration_ISBI_three_2.txt
python run_training.py configuration_ISBI_three_3.txt
python run_training.py configuration_ISBI_three_4.txt
python run_training.py configuration_ISBI_three_5.txt
python run_training.py configuration_ISBI_three_6.txt
python run_training.py configuration_ISBI_three_7.txt


python run_testing.py configuration_ISBI_three_1.txt
python run_testing.py configuration_ISBI_three_2.txt
python run_testing.py configuration_ISBI_three_3.txt
python run_testing.py configuration_ISBI_three_4.txt
python run_testing.py configuration_ISBI_three_5.txt
python run_testing.py configuration_ISBI_three_6.txt
python run_testing.py configuration_ISBI_three_7.txt
